apps/siege/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^$', views.manage, name='manage'),
    url(r'^armies$', views.show_armies, name='armies'),
    url(r'^new$', views.create_siege, name='new'),
    url(r'^armies/new$', views.create_army, name='newarmy'),
    url(r'^(?P<siege>\d+)/addarmy$', views.add_army_tosiege, name='add_army'),
    url(r'^(?P<siege>\d+)$', views.edit_siege, name='edit_siege'),
    url(r'^armies/(?P<army>\d+)$', views.save_army, name="update_army"),
    url(r'^(?P<siege>\d+)/armies/(?P<army>\d+)$', views.update_siegearmy, name="update_siegearmy"),
    url(r'^cities$', views.show_cities, name='cities'),
    url(r'^cities/new$', views.create_city, name='newcity'),
    url(r'^cities/(?P<city>\d+)$', views.save_city, name="update_city"),
    url(r'^(?P<siege>\d+)/schedule$', views.schedule, name="schedule"),
    url(r'^myschedule$', views.player_schedule, name="myschedule"),
    )

sinserver/urls.py
from django.conf.urls import url, include
from django.contrib import admin

"""sinserver URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.logreg.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^siege/', include('apps.siege.urls')),
    url(r'^combats/', include('apps.combats.urls')),
]

apps/siege/models.py
from __future__ import unicode_literals
from ..logreg.models import Player
from django.db import models
from django import forms
from django.forms import ModelForm, DateTimeInput
from datetime import datetime

# Create your models here.
class Siege(models.Model):
    target_player = models.CharField(max_length = 100)
    target_city = models.CharField(max_length = 100)
    x_coord = models.SmallIntegerField()
    y_coord = models.SmallIntegerField()
    landing_time = models.DateTimeField(default=datetime.now())
    N = models.BooleanField(default=False)
    NE = models.BooleanField(default=False)
    E = models.BooleanField(default=False)
    SE = models.BooleanField(default=False)
    S = models.BooleanField(default=False)
    SW = models.BooleanField(default=False)
    W = models.BooleanField(default=False)
    NW = models.BooleanField(default=False)
    DIR = models.BooleanField(default=True)
    def __str__(self):
        return str(self.target_player) + "-- " + str(self.target_city)
    class Meta:
        db_table = 'sieges'

class SiegeForm(ModelForm):
    landing_time = forms.DateTimeField(input_formats=['%m/%d/%Y %I:%M %p', '%m-%d-%Y %H:%M:%S'])
    class Meta:
        model = Siege
        fields = (
            'target_player',
            'target_city',
            'x_coord',
            'y_coord',
            'landing_time',
            'N',
            'NE',
            'E',
            'SE',
            'S',
            'SW',
            'W',
            'NW',
            )


class City(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    name = models.CharField(max_length = 100)
    x_coord = models.SmallIntegerField()
    y_coord = models.SmallIntegerField()
    region = models.CharField(max_length = 100)
    def __unicode__(self):
        return str(self.player) + "-" + str(self.name)
    class Meta:
        db_table = 'cities'

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = (
            'name',
            'player',
            'x_coord',
            'y_coord',
            'region'
        )


class Army(models.Model):
    TROOPTYPE_CHOICES = (
        ('SP_T1', 'T1 Spears'),
        ('SP_T2', 'T2 Spears'),
        ('BOW_T1', 'T1 Bows'),
        ('BOW_T2', 'T2 Bows'),
        ('INF_T1', 'T1 Infantry'),
        ('INF_T2', 'T2 Infantry'),
        ('CAV_T1', 'T1 Cavalry'),
        ('CAV_T2', 'T2 Cavalry'),
        ('MIX_SP', 'Mixed spears'),
        ('MIX_BOW', 'Mixed bows'),
        ('MIX_INF', 'Mixed infantry'),
        ('MIX_CAV', 'Mixed cav'),
        ('MIX', 'Kitchen sink')
    )

    ELITE_CHOICES = (
        ('CAV', 'Anti-Cavalry'),
        ('INF', 'Anti-Infantry'),
        ('BOW', 'Anti-Bow')
    )

    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    troop_type = models.CharField(choices=TROOPTYPE_CHOICES, max_length = 100)
    troop_count = models.IntegerField(default=0)
    siege_engines = models.SmallIntegerField(default=0)
    wall_engines = models.SmallIntegerField(default=0)
    speed = models.DecimalField(max_digits=5, decimal_places=3,default=0)
    elite_divs_number = models.SmallIntegerField()
    elite_type = models.CharField(choices=ELITE_CHOICES, max_length = 100, blank=True)
    away = models.BooleanField(default=False)
    def __str__(self):
        return str(self.player) + "-" + str(self.city) + "-" + str(self.troop_type) + "-" + str(self.troop_count)
    class Meta:
        db_table = 'armies'

class ArmyForm(ModelForm):
    class Meta:
        model = Army
        fields = (
            'player',
            'city',
            'troop_type',
            'troop_count',
            'speed',
            'siege_engines',
            'wall_engines',
            'elite_type',
            'elite_divs_number',
            )


class Siege_army(models.Model):
    SQUARES = (
        ('N', 'North'),
        ('NE', 'Northeast'),
        ('E', 'East'),
        ('SE', 'Southeast'),
        ('S', 'South'),
        ('SW', 'Southwest'),
        ('W', 'West'),
        ('NW', 'Northwest'),
        ('DIR', 'Direct')
        )
    
    ORDERS = (
        ('occupy', 'occupy'),
        ('attack', 'attack'),
        ('blockade', 'blockade'),
        ('siege', 'siege')
        )

    siege_id = models.ForeignKey(Siege, on_delete=models.CASCADE)
    army_id = models.ForeignKey(Army, on_delete=models.CASCADE)
    player_id = models.ForeignKey(Player, on_delete=models.CASCADE)
    siege_square = models.CharField(max_length = 3, choices=SQUARES)
    time_offset = models.IntegerField(default=0)
    time_sent = models.DateTimeField(null=True)
    orders = models.CharField(choices=ORDERS, max_length = 30, default='occupy')
    class Meta:
        db_table = 'siege_armies'
    
    

apps/siege/views.py
from __future__ import division
import json
import re
from datetime import datetime, timedelta
from django.shortcuts import render, redirect, render_to_response
from django.utils import timezone
from django import db, template
from django.http import JsonResponse, HttpResponse
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.forms.models import model_to_dict
from math import sqrt
from .models import (Siege, Siege_army, City, Army, SiegeForm, Player, ArmyForm, CityForm)
from .templatetags import siege_tags
from .helper import *

date_format = "%m-%d-%Y %H:%M:%S"
date_format2 = "%"
offset_regex = re.compile(r'(-?)(\d{2,}):([0-5][0-9]):([0-5][0-9])')

# Landing page
@login_required(login_url='/', redirect_field_name=None)
def manage(request):
    sieges = {
        'sieges': Siege.objects.all(),
        'form': SiegeForm(label_suffix="")
        }
    return render(request, 'siege/manage.html', sieges)


# Create new siege
@login_required(login_url='/', redirect_field_name=None)
def create_siege(request):
    if request.method == "POST":
        form = SiegeForm(request.POST)
        print form
        if form.is_valid():
            siege = form.save(commit=False)
            siege.save()
            return redirect('manage')
        else:
            print form.errors
    else:
        form = SiegeForm()
    return render(request, 'siege/manage.html', {'form': form})


# Render siege editing page
@login_required(login_url='/', redirect_field_name=None)
def edit_siege(request, siege):
    # Take the user to the edit siege page
    if request.method == 'GET':
        context = {}
        inner_queryset = set(Siege_army.objects.all())
        army_query = Army.objects.filter(siege_army__isnull=True)
        the_siege = model_to_dict(Siege.objects.get(id=siege))
        context['armies'] = [(lambda x: model_to_dict(x))(x) for x in army_query]

        for idx, army in enumerate(context['armies']):
            print "%%%%%%%%%%%%, %s" % army
            city = City.objects.get(id=army['city'])
            army['city'] = city.name
            army['player'] = Player.objects.get(id=army['player']).__str__()
            distance = calc_dist(city.x_coord, city.y_coord, the_siege['x_coord'], the_siege['y_coord'])
            army['dist'] = "%.3f" % (distance)
            travel_time = calc_time(army['speed'], distance)
            army['time'] = "%.3f" % (travel_time)
            launch_time = calc_launch_time(the_siege['landing_time'], travel_time)
            army['launch_time'] = datetime.strftime(launch_time, date_format)
            army['troop_type'] = army_query[idx].get_troop_type_display()
            army['engines'] = "%s/%s" % (army_query[idx].siege_engines, army_query[idx].wall_engines)
        squares = [k for (k,v) in the_siege.items() if (v == True and k != "id")]
        the_siege['landing_time'] = datetime.strftime(the_siege['landing_time'], date_format)
        context['siege'] = the_siege
        context['siege_armies'] = inner_queryset
        context['squares'] = squares
        context['orders'] = [x[0] for x in Siege_army.ORDERS]

        print "Number of queries made: {0}".format(len(db.connection.queries))
        return render(request, 'siege/edit_siege.html', context)
    # Delete a siege and re-render manage.html
    elif request.method == 'DELETE':
        the_siege = Siege.objects.get(id=int(siege))
        the_siege.delete()
        return HttpResponse("success")
    elif request.method == "POST":
        print request.POST
        thesiege = Siege.objects.get(id=int(siege))
        form = SiegeForm(request.POST, instance=thesiege)
        print form
        if form.is_valid():
            siegeObj = form.save(commit=False)
            siegeObj.save()
            return redirect('/siege/'+siege)
        else:
            print form.errors
        return render(request, 'siege/manage.html', {'form': form})


# Add army to siege
@login_required(login_url='/', redirect_field_name=None)
def add_army_tosiege(request, siege):
    if request.method == 'GET':
        pass
    elif request.method == 'POST':
        offset = offset_fromstring(request.POST["Offset"])
        if request.POST["Square"] == "id":
            square = "DIR"
        else:
            square = request.POST["Square"]
        the_siege = Siege.objects.get(id=int(siege))
        the_army = Army.objects.get(id=int(request.POST["armyId"]))
        newSiegeArmy = Siege_army(siege_id=the_siege, army_id=the_army, player_id=the_army.player, siege_square=square, time_offset=offset, orders=request.POST["Orders"])
        newSiegeArmy.save()
        partial_context = {}
        partial_context['siege'] = {}
        partial_context['siege']['id'] = siege
        context = siege_tags.siege_armies_partial(partial_context)
        return render_to_response('siege/siege_armies_partial.html', context)


# Update siege army
@login_required(login_url='/', redirect_field_name=None)
def update_siegearmy(request, siege, army):
    if request.method == 'PUT':
        print "%%%%%%%%%%%%%%%%%%%%"
        body = json.loads(request.body.decode('utf-8'))
        siege_army = Siege_army.objects.get(id=int(army))
        offset = offset_fromstring(body['offset'])
        print "Siege army changes: %s, offset: %s" % (body, offset)
        siege_army.time_offset = offset
        siege_army.siege_square = body['siege_square']
        siege_army.orders = body['orders']
        siege_army.save()
        return HttpResponse("Mkay!")
    elif request.method == 'DELETE':
        siege_army = Siege_army.objects.get(id=int(army))
        siege_army.delete()
        return HttpResponse("1 siege deleted")


# Get armies and render armies page
@login_required(login_url='/', redirect_field_name=None)
def show_armies(request):
    context = {}
    player = request.user.username
    context['player_id'] = request.user.player.id
    context['player'] = player
    cities = [(lambda x: model_to_dict(x))(x) for x in City.objects.filter(player=request.user.player)]
    print "Cities: {0}".format(cities)
    cities_list = [{'name':x['name'], 'id':x['id']} for x in cities]
    context['cities'] = cities_list
    armies = Army.objects.select_related('city').filter(player=request.user.player)
    context['armies'] = [(lambda x: model_to_dict(x))(x) for x in armies]
    for idx, army in enumerate(context['armies']):
        context['armies'][idx]['city'] = armies[idx].city.name
        context['armies'][idx]['troop_type'] = armies[idx].get_troop_type_display()
        context['armies'][idx]['troop_type_info'] = armies[idx].troop_type
    context['form'] = ArmyForm(label_suffix = "")
    print context
    return render(request, 'siege/armies.html', context)


# Create new army
@login_required(login_url='/', redirect_field_name=None)
def create_army(request):
    player = request.user.username
    if request.method == "POST":
        form = ArmyForm(request.POST)
        if form.is_valid():
            army = form.save(commit=False)
            print "Army: {0}".format(army)
            army.save()
            return redirect('armies')
        else:
            print "Errors: {0}".format(form.errors)
    else:
        form = ArmyForm()
    return render(request, 'siege/armies.html', {'form': form, 'player': player})


# Update army
@login_required(login_url='/', redirect_field_name=None)
def save_army(request, army):
    thearmy = Army.objects.get(id=int(army))
    print ("$$$$$$$$$$$$$$$$$$$$$$ POST data: %s" % request.POST)
    if request.method == "POST":
        if "ajax" in request.POST:
            speed = float(request.POST["speed"])
            thearmy.speed = speed
            if "troop_count" in request.POST:
                thearmy.troop_count = int(request.POST["troop_count"])
            thearmy.save()
            return HttpResponse("success")
        form = ArmyForm(request.POST, instance=thearmy)
        if form.is_valid():
            form.save()
            return redirect("armies")
        return HttpResponse("Form was invalid, saving failed")
    elif request.method == "DELETE":
        thearmy = Army.objects.get(id=int(army))
        thearmy.delete()
        return HttpResponse("1 army deleted")


# Get cities and render cities page
@login_required(login_url='/', redirect_field_name=None)
def show_cities(request):
    context = {}
    context['player'] = request.user.username
    context['player_id'] = request.user.player.id
    context['cities'] = City.objects.filter(player=request.user.player)
    return render(request, 'siege/towns.html', context)


# Create new city
@login_required(login_url='/', redirect_field_name=None)
def create_city(request):
    print "Creating a city, player: %s" % request.user.player.id
    player = request.user.username
    print request.POST
    if request.method == "POST":
        form = CityForm(request.POST)
        if form.is_valid():
            city = form.save(commit=False)
            print city
            city.save()
            return redirect('cities')
        else:
            print "Errors: {0}".format(form.errors)
    else:
        form = CityForm()
    return render(request, 'siege/towns.html', {'form': form, 'player': player})


# Update city
@login_required(login_url='/', redirect_field_name=None)
def save_city(request, city):
    if request.method == "DELETE":
        thecity = City.objects.get(id=int(city))
        thecity.delete()
        return HttpResponse("1 city deleted")
    elif request.method == "POST":
        print ("%%%%%%%%%%%%%%%%%%%%% POST data: {0}".format(request.POST))
        player = request.user.username
        the_city = City.objects.get(id=int(city))
        form = CityForm(request.POST, instance=the_city)
        if form.is_valid():
            form.save()
            return redirect('cities')

apps/siege/templates/siege/edit_siege.html
{% extends "sinserver/base.html" %}
{% block content %}
{% load staticfiles %}
    <script src="{% static 'siege/js/siege.js' %}"></script>
    {% load siege_tags %}
    <h1>Siege Plan</h1>
    <table id="sieges" class="mytable table mytable-compact">
        <thead>
            <tr>
                <th>Player</th>
                <th>City</th>
                <th>X</th>
                <th>Y</th>
                <th>Squares</th>
                <th>Landing time</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tr>
            <td class="player">{{siege.target_player}}</td>
            <td class="city">{{siege.target_city}}</td>
            <td class="x">{{siege.x_coord}}</td>
            <td class="y">{{siege.y_coord}}</td>
            <td class="squares">{%if siege.N%}N {%endif%}<!--
                -->{%if siege.NE%}NE {%endif%}<!--
                -->{%if siege.E%}E {%endif%}<!--
                -->{%if siege.SE%}SE {%endif%}<!--
                -->{%if siege.S%}S {%endif%}<!--
                -->{%if siege.SW%}SW {%endif%}<!--
                -->{%if siege.W%}W {%endif%}<!--
                -->{%if siege.NW%}NW{%endif%}<!--
            --></td>
            <td class="landing">{{siege.landing_time}}</td>
            <td nowrap>
                <button id="{{ siege.id }}" class="edit btn btn-success">Edit</button>
                <button id="{{ siege.id }}" class="delete btn btn-danger">Delete</button>
                <a class="btn btn-info" href="/siege/{{ siege.id }}/schedule">View Schedule</a>
            </td>
        </tr>
    </table>
    <div class="form-row" hidden="true">
        <form id="edit-siege" action="" method="POST">{% csrf_token %}
            <div class="form-cell"><label>Player</label><input type="text" name="target_player" id="id_target_player"></div>
            <div class="form-cell"><label>Target City</label><input type="text" name="target_city" id="id_target_city"></div>
            <div class="form-cell"><label>X</label><input type="text" name="x_coord" id="id_x_coord"></div>
            <div class="form-cell"><label>Y</label><input type="text" name="y_coord" id="id_y_coord"></div>
            <div class="form-cell"><label style="display: block">Landing Time, UTC</label>
            <div class="input-group date" id="dp" style="display:inline-flex;">
                <input id="id_landing_time" name="landing_time" type="text" style="width:100%"><!--
                --><span class="input-group-addon" style="padding: 6px 18px;"><!--
                --><span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="form-cell sq">
                <div class="chbox"><label for="id_N">N</label><input id="id_N" name="N" type="checkbox"></div>
                <div class="chbox"><label for="id_NE">NE</label><input id="id_NE" name="NE" type="checkbox"></div>
                <div class="chbox"><label for="id_E">E</label><input id="id_E" name="E" type="checkbox"></div>
                <div class="chbox"><label for="id_SE">SE</label><input id="id_SE" name="SE" type="checkbox"></div>
                <div class="chbox"><label for="id_S">S</label><input id="id_S" name="S" type="checkbox"></div>
                <div class="chbox"><label for="id_SW">SW</label><input id="id_SW" name="SW" type="checkbox"></div>
                <div class="chbox"><label for="id_W">W</label><input id="id_W" name="W" type="checkbox"></div>
                <div class="chbox"><label for="id_NW">NW</label><input id="id_NW" name="NW" type="checkbox"></div>
            </div>
        <script type="text/javascript">
            $(function(){
                $('#dp').datetimepicker({useUtc: true, format: "MM-DD-YYYY HH:mm:ss"});
            });
        </script>
            <button id="siege-button" type="submit" class="btn btn-primary">Save Siege</button>
        </form>
    </div>
    <div id="castle-toggle"></div>
    <div id="layout" hidden="true">
        <div class="siege-plan" id="NW"></div><!--
        --><div class="siege-plan" id="N"></div><!--
        --><div class="siege-plan" id="NE"></div><!--
        --><div class="siege-plan" id="W"></div><!--
        --><div class="siege-plan" id="DIR"></div><!--
        --><div class="siege-plan" id="E"></div><!--
        --><div class="siege-plan" id="SW"></div><!--
        --><div class="siege-plan" id="S"></div><!--
        --><div class="siege-plan" id="SE"></div>
    </div>
    <h3>Assign Armies</h3>
    <table id="unassignedArmies" class="mytable table table-paginated table-bordered siegetable">
        <thead>
        <tr>
            <th>Player</th>
            <th>City</th>
            <th>Troop type</th>
            <th>Count</th>
            <th>Engines</th>
            <th>Speed</th>
            <th>Distance</th>
            <th>ETA, h</th>
            <th>Offset</th>
            <th>Square</th>
            <th>Orders</th>
            <th>Launch Time, UTC</th>
            <th>Action</th>
            </tr>
        </thead>
        <tbody>
        {% for army in armies %}
        <tr id="{{army.id}}">
            <td>{{army.player}}</td>
            <td>{{army.city}}</td>
            <td nowrap>{{army.troop_type}}</td>
            <td>{{army.troop_count}}</td>
            <td nowrap>{{army.engines}}</td>
            <td class="speed">
                <p>{{army.speed}}</p>
                <input type='text' class='speedInput' hidden="true">
            </td>
            <td class="dist">{{army.dist}}</td>
            <td class="eta">{{army.time}}</td>
            <td class="offset"><input class="offsetInput" type="text" placeholder="hh:mm:ss/-hh:mm:ss"></td>
            <td>
                <select id="square" name="square">
                    {% for square in squares %}
                    <option value="{{square}}">{{square}}</option>
                    {% endfor %}
                </select>
            </td>
            <td >
                <select id="orders" name="orders">
                {% for order in orders %}
                <option value="{{order}}">{{order}}</option>
                {% endfor %}
            </td>
            <td class="timer" data-toggle="tooltip" data-placement="top">{{army.launch_time}}</td>
            <td nowrap style="text-align: justify;"><span id="addSiege-{{army.id}}" class="addsiege glyphicon glyphicon-plus orange"></span>
            <span class="glyphicon glyphicon-ok green saveArmy"></span></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <h3>Armies in Siege</h3>
    <div id="assigned-partial">
    {% siege_armies_partial %}
    </div>
    {% endblock %}
    

apps/siege/templates/siege/manage.html
{% extends "sinserver/base.html" %}
{% block content %}
    {% load staticfiles %}
    <script src="{% static 'siege/js/manage.js' %}"></script>
    <h1>Siege dashboard</h1>
    <h3>Current Sieges</h3>
    <table class="mytable table sieges">
        <thead>
            <tr>
                <th>Player</th>
                <th>City</th>
                <th>Squares</th>
                <th>Landing Time</th>
                <th>Actions</th>
            </tr>
        </thead>
            {% for siege in sieges %}
                <tr>
                    <td>{{ siege.target_player }}</td>
                    <td>{{ siege.target_city }}</td>
                    <td>{% if siege.N %}N {%endif%}<!--
                    -->{% if siege.NE %}NE {%endif%}<!--
                    -->{% if siege.E %}E {%endif%}<!--
                    -->{% if siege.SE %}SE {%endif%}<!--
                    -->{% if siege.S %}S {%endif%}<!--
                    -->{% if siege.SW %}SW {%endif%}<!--
                    -->{% if siege.W %}W {%endif%}<!--
                    -->{% if siege.NW %}NW {%endif%}</td>
                    <td>{{ siege.landing_time }}</td>
                    <td>
                        <button id="{{ siege.id }}" class="edit btn btn-success">Edit</button>
                        <button id="{{ siege.id }}" class="delete btn btn-danger">Delete</button>
                        <a class="btn btn-info" href="/siege/{{ siege.id }}/schedule">View Schedule</a>
                    </td>
                </tr>
            {% endfor %}
    </table>

    <div class="wrapper-left">
    <h3>New Siege</h3>
    <form id="siegeForm" action="{% url 'new' %}" method='POST'>{% csrf_token %}
        <label for="id_target_player">Target player</label><!--
        --><input id="id_target_player" maxlength="100" name="target_player" type="text">
        <label for="id_target_city">Target city</label><!--
        --><input id="id_target_city" maxlength="100" name="target_city" type="text">
        <label for="id_x_coord">X coord</label><!--
        --><input id="id_x_coord" name="x_coord" type="text">
        <label for="id_y_coord">Y coord</label><!--
        --><input id="id_y_coord" name="y_coord" type="text">
        <label for="id_landing_time">Landing time, UTC</label><!--
        -->
        <div class="form-group">
            <div class="input-group date" id="dp" style="display:inline-flex;">
                <input id="id_landing_time" name="landing_time" type="text" style="width:100%"><!--
                --><span class="input-group-addon" style="padding: 6px 18px;"><!--
                --><span class="glyphicon glyphicon-calendar"></span>
                    </span>
            </div>
        </div>
        <script type="text/javascript">
            $(function(){
                $('#dp').datetimepicker({useUtc: true});
            });
        </script>
        <label for="id_N">N</label><input id="id_N" name="N" type="checkbox">
        <label for="id_NE">NE</label><input id="id_NE" name="NE" type="checkbox">
        <label for="id_E">E</label><input id="id_E" name="E" type="checkbox">
        <label for="id_SE">SE</label><input id="id_SE" name="SE" type="checkbox">
        <label for="id_S">S</label><input id="id_S" name="S" type="checkbox">
        <label for="id_SW">SW</label><input id="id_SW" name="SW" type="checkbox">
        <label for="id_W">W</label><input id="id_W" name="W" type="checkbox">
        <label for="id_NW">NW</label><input id="id_NW" name="NW" type="checkbox">

        <button id="siege-button" button type="submit" class="btn btn-primary">Add Siege</button>
    </form>
    </div>
    {% endblock %}
    <script></script>

apps/siege/templates/siege/towns.html
{% extends "sinserver/base.html" %}
{% block content %}
{% load staticfiles %}
<script src="{% static 'siege/js/towns.js' %}"></script>
<h1>{{player}}'s cities</h1>
<table class="mytable table mytable-compact">
        <thead>
            <th>Player</th>
            <th>City Name</th>
            <th>X</th>
            <th>Y</th>
            <th>Region</th>
            <th>Action</th>
        </thead>
        {% for city in cities %}
        <tr id="{{city.id}}">
            <td>{{player}}</td>
            <td class="name">{{city.name}}</td>
            <td class="x_coord">{{city.x_coord}}</td>
            <td class="y_coord">{{city.y_coord}}</td>
            <td class="region">{{city.region}}</td>
            <td><button class="edit btn btn-success">Edit</button>
            <button class="delete btn btn-danger">Delete</button>
            </td>
        </tr>
        {% endfor %}
    </table>
    <div class="wrapper-left">
    <form id="armyForm" action="{% url 'newcity' %}" method = 'POST'>{%csrf_token%}
        <input type="hidden" name="player" value={{player_id}}>
        <label class="army-label" for="id_name">City Name</label>
        <input id="id_name" name="name" type="text">
        <label class="army-label" for="id_region">Region</label>
        <input id="id_region" name="region" type="text">
        <label class="army-label" for="id_x_coord">X coord</label>
        <input class="input-number" id="id_x_coord" name="x_coord" type="text" value="0">
        <label class="army-label" for="id_y_coord">Y coord</label>
        <input class="input-number" id="id_y_coord" name="y_coord" type="text" value="0">
    <button id="army-button" button type="submit" class="btn btn-primary">Add City</button>
    </form>
    </div>
{% endblock %}